# Generated by Django 6.0.4 on 2026-05-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stitches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Tops', 'Tops'), ('Skirts', 'Skirts'), ('Bags', 'Bags'), ('Scrunchies', 'Scrunchies'), ('Hair Bands', 'Hair Bands'), ('Bows', 'Bows'), ('Handkerchiefs', 'Handkerchiefs'), ('Others', 'Others')], max_length=100),
        ),
    ]
