# Generated by Django 6.0.4 on 2026-05-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stitches', '0004_product_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fabric',
        ),
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='colour_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Awaiting Confirmation', 'Awaiting Confirmation'), ('Half Paid', 'Half Paid'), ('Fully Paid', 'Fully Paid')], default='Unpaid', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='order',
            name='transfer_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='colour',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
